### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by roshavagarga** [BreadMoirai/OneClickCrafting#8]
Per title, not working with 1.20.2 atm.

**Comment by Zorklis** [comment]
YES, 1.20.2 support please

**Comment by Coobik1234** [comment]
Also 1.20.4 please

**Comment by BreadMoirai** [comment]
see 1.7.2 & 1.7.3

**Comment by Zorklis** [comment]
Thank you for 1.20.4 :) thankfully this mod is not gone and forgotten
